linters-settings:
  funlen:
    lines: 120
    statements: 80
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 20
  goimports:
#    local-prefixes: git.code.oa.com
  govet:
    check-shadowing: false
  lll:
    line-length: 120
  errcheck:
    check-type-assertions: true
  nestif:
    min-complexity: 4

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - funlen
    - goconst
    - gocyclo
    - gofmt
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - goimports
    - gosimple
    - govet
    - lll
    - rowserrcheck
    - errcheck
    - unused
    - varcheck
    - nestif
    - sqlclosecheck
    - bodyclose

run:
  skip-dirs:
      # - test/testdata_etc

issues:
  exclude-use-default: false

service:
  golangci-lint-version: 1.23.x
